-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Products Table
create table if not exists products (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  price text not null,
  image text,
  category text,
  description text,
  is_visible boolean default true,
  colors text[], -- Storing colors as an array of hex strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for products
alter table products enable row level security;

-- Policy: Everyone can view visible products
create policy "Products are viewable by everyone" 
  on products for select 
  using (true);

-- Policy: Only authenticated users (admins) can insert/update/delete
-- Note: For now, allowing public insert/update for demo purposes if anon key is used for admin.
-- Ideally, you should restrict this to specific user roles.
create policy "Enable all access for all users" 
  on products for all 
  using (true) 
  with check (true);


-- Orders Table
create table if not exists orders (
  id uuid primary key default uuid_generate_v4(),
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  comment text,
  items jsonb not null, -- Stores the array of items in the order
  total numeric not null,
  status text check (status in ('new', 'processing', 'completed', 'cancelled')) default 'new',
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for orders
alter table orders enable row level security;

-- Policy: Everyone can create orders
create policy "Anyone can create orders" 
  on orders for insert 
  with check (true);

-- Policy: Everyone can view orders (for admin panel usage)
-- In a real app, this should be restricted to the creator or admins
create policy "Orders are viewable by everyone" 
  on orders for select 
  using (true);

-- Policy: Everyone can update orders (for admin panel usage)
create policy "Orders are updatable by everyone" 
  on orders for update 
  using (true);


-- Translations Table
create table if not exists translations (
  id bigint generated by default as identity primary key,
  key text not null,
  lang text not null,
  value text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (key, lang)
);

-- Enable RLS for translations
alter table translations enable row level security;

-- Policy: Everyone can view translations
create policy "Translations are viewable by everyone" 
  on translations for select 
  using (true);

-- Policy: Enable all access for all users (for admin panel editing)
create policy "Enable write access for all users" 
  on translations for all 
  using (true) 
  with check (true);


-- Sections Table (for visibility toggles)
create table if not exists sections (
  id text primary key,
  is_visible boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for sections
alter table sections enable row level security;

-- Policy: Everyone can view sections
create policy "Sections are viewable by everyone" 
  on sections for select 
  using (true);

-- Policy: Enable all access for all users (for admin panel editing)
create policy "Enable write access for all users" 
  on sections for all 
  using (true) 
  with check (true);
